name: docker-centos-8/release

on:
  push:
    branches: [ release ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update -y
        sudo apt install yq -y

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file centos-8.Dockerfile --tag cs1193/centos-8:latest


    - name: Push the Docker image
      run: docker push cs1193/centos-8:latest
